langueage: python

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5

install:
 - sudo apt-get install python3.5 libnetfilter-queue-dev python3.5-dev

python:
 - "3.5"
  
script: python3.5 --version && python3.5 hakku -t challenge
