langueage: python

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5

install:
 - sudo apt-get install python3.5

python:
 - "3.5"
  
script: python3 --version && python3 usploit -t challenge
